kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: pto-proxy
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/pto-proxy/pto-proxy:{{version}}
  port: 8080
  ingresses:
    - https://pto-proxy.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  liveness:
    path: /internal/health/liveness
    initialDelay: 30
  readiness:
    path: /internal/health/readiness
    initialDelay: 30
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 512Mi
  accessPolicy:
      inbound:
        rules:
          - application: poa-arbeidssokerregistrering
            namespace: paw
          - application: veientilarbeid
            namespace: paw
          - application: arbeidssokerregistrering
            namespace: paw
          - application: veilarbregistrering
            namespace: paw
          - application: veiviserarbeidssoker
            namespace: paw
          - application: behovsvurdering
          - application: aktivitetsplan
          - application: arbeidsrettet-dialog
          - application: start-samtale
          - application: flex-gateway
            namespace: flex
      external:
        - host: api-gw.oera.no
  envFrom:
    - secret: pto-proxy-api-gw-keys
    - configmap: loginservice-idporten
  env:
    - name: API_GW_URL
      value: https://api-gw.oera.no

